### ISSUE TITLE
Does not keep aspect ratio of images

### ISSUE THREAD

**Issue by StarAzure** [neptunian/react-photo-gallery#100]
If the height and width number has to be passed by the user or some code in the component, then react-photo-gallery should not claim that it keeps the aspect ratio of images. I have seen a few other issues which was ignored/closed saying it should be passed by the component.
Responsive meaning = changes height/width automatically without distorting images. This is not true here.
I have images that can be uploaded by users in various sizes. I have no way of knowing what the aspect ratio is ahead of time. 

        width: 15,
        height: '',

in the above code, I am specifying a width and was hoping that the height would be calculated automatically just like normal css does - But I get error 
"Invalid prop `photos[0].height` of type `string` supplied to `Gallery`, expected `number`."
Why not make height optional so that it can be auto thus keeping aspect ratio of images?

**Comment by neptunian** [comment]
it maintains the aspect ratio given the size of any device.  its not possible for it to be responsive otherewise.  i need image dimensions ahead of time otherwise i'd have to wait till the image was done loading and find it myself.  thanks for your opinion.

**Comment by StarAzure** [comment]
You cant keep ignoring this very important aspect of "photo gallery". Its very important so please consider it as this is not the first issue asking about it.  I would care more for my photos to not look distorted which spoils this otherwise good app that you have written. 
You say js is not css but actually your js code translates the sizes to css/styles. if you see the image has style="width: 230px;  height: 230px;" - This comes from the calculations in your js code. I would like to just set height: auto but your code does not allow me to do that.
I am not a js expert but I am going to either try to assign a height: auto to the images and if not possible will have to remove react-image-gallery which I hate to do because I have invested time in using it. !!

**Comment by vincentvpham** [comment]
adding `object-fit: cover` to the gallery img css is a simple workaround

**Comment by tamb** [comment]
> 
> 
> adding `object-fit: cover` to the gallery img css is a simple workaround

Great stuff!:
See this table for browser support:
https://caniuse.com/object-fit

**Comment by KnoxMajor** [comment]
If you would like to keep the original aspect ratio, this is how I solved it:
```
import React, { useState, useEffect } from "react";
import Gallery from "react-photo-gallery";

export default function MasonryPhotoGallery({
    photos /* can be array of form-data imgs, check code below for that use case. OR can just be an array of urls (ex. [{url:'foo.com/bar.jpg'}, {url:'foo.com/bar.jpg'}]  )*/
}) {

  const [images, setImages] = useState([]);    
  
  
  const aspectRatio = (height, width) => {
    if (height > width) {
        return { width: 1, height: height / width }
    } else {
        return { height: 1, width: width / height }
    }
  }
  
  let photosForGallery = (imgArr) => {
    let imgs = [];
    imgArr.forEach(img => {
        var mockImage = document.createElement('img');
  
        /* do this if you are passing in user submitted form-data images
        var src = URL.createObjectURL(img);
        */
  
        /* if just using urls set 'src' to whatever in your object is the url to your image */
        var src = img.url;
  
        mockImage.src = src;
        mockImage.onload = function () {
            let aspect = aspectRatio(mockImage.height, mockImage.width)
            imgs.push({
                src: src,
                width: aspect.width,
                height: aspect.height
            })
        }
    })
    return imgs
  }
  
  /* when photos is passed into the component run the function and update the state */
  useEffect(() => {
      if (photos.length > 0) {
          setImages(photosForGallery(photos))
      }
  }, [photos]);

  return (
    <div style={{width: '100%'}}>
       <Gallery photos={images}/>
    </div>
  );
}
```
