### ISSUE TITLE
Dynamic num of columns by image thumbnail size

### ISSUE THREAD

**Issue by OriAmir** [neptunian/react-photo-gallery#105]
Hi, **tnx** for great library .
I want to achieve something like that:
I want photo gallery with same height for all thumbnail images , but different width - that will calculate by my wanted thumbnail max height .

The problem is that the thumbnail images is always in same size and very very big , it's always 3 in a row max by default not matter what I put inside 'width' and 'height' props . I try to play with 'columns' property but it doesn't do the work for me.

** I get images urls from server , so I DON'T know image width/height , it's dynamically .

This is the code I try with 150 height of thumbnail ,but as i said what i put inside 'height' and 'width' not change anything. 

```
 const PHOTO_SET = this.props.images.map(img => ({
      src: img.url,
      width: calculateAspectRatioFit(img.width, img.height, img.width, 150)
        .width,
      height: calculateAspectRatioFit(img.width, img.height, img.width, 150)
        .height
    }));
```

```
const calculateAspectRatioFit = (
    srcWidth,
    srcHeight,
    maxWidth,
    maxHeight
  ) => {
    var ratio = Math.min(maxWidth / srcWidth, maxHeight / srcHeight);
    return { width: srcWidth * ratio, height: srcHeight * ratio };
  };
```

I try also to calculate num of colmuns by screen width:

```
  <Gallery
          columns={this.state.width / 150} //Width is always calculated when screen size change
          photos={PHOTO_SET}
        />
```
The problem here is that thumbnail size is not as I want again... it's kind of constant .

Can anyone give me some advice?
**Thanks!**

**Comment by neptunian** [comment]
Heights of the rows will vary based on the total aspect ratio of each image.  The idea is you have to find a common height to maintain the aspect ratio of all images and for them to all fit on a single row.  So the rows will only be the same height if all your images have the same aspect ratio.  For example if you want them all to be squares then type in width:1, height: 1 and all the rows should then have the same height.

**Comment by OriAmir** [comment]
@neptunian 
Thanks for your answer . So, you tell me actually that this library is supported just for hard-coded images  ?
If I load my images URL from server I can't organize my images as I want ?( my wanted height for thumbnail? or same constant size for them ?)
It's sound's wired because who set his images hard-coded if the library is big enough .

**Comment by neptunian** [comment]
Most apis return height and width properties of an image object that are added to an array you pass into the Gallery.

**Comment by OriAmir** [comment]
@neptunian I get the image url, width, height of the image from my api's also but I don't understand how it's help me ? I try to set my wanted height but actually it's calculate this alone.. maybe I don't understand something..
Thanks again!
