### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by eriktiekstra** [neptunian/react-photo-gallery#108]
I implemented this inside a project I am working on, all seems to work fine but somehow errors pop-up on Sentry.io. The error I get is `ResizeObserver loop limit exceeded`. When I check the console, none of the errors are popping up. When I activate a Chrome extension (Javascript errors notifier) I am able to see the error.  

The page where the gallery is implemented: https://www.weahead.se/blog/lissabon-2018

**Comment by daminufe** [comment]
+1 here. 
I am getting these errors from Rollbar in production only.
![image](https://user-images.githubusercontent.com/4832774/46861207-68ee9700-ce12-11e8-80e3-cfe2cd04b65f.png)

**Comment by kirananto** [comment]
Any update on this.. this is still happening for me. 😞
