### ISSUE TITLE
SSR app compatible

### ISSUE THREAD

**Issue by Fi1osof** [neptunian/react-photo-gallery#109]
In docs says "SSR app compatible".
Is this right? 
Gallery component initialize with containerWidth = 0; https://github.com/neptunian/react-photo-gallery/blob/master/src/Gallery.js#L9
In render, if containerWidth == 0, return empty div. https://github.com/neptunian/react-photo-gallery/blob/master/src/Gallery.js#L37
Result: SSR return empty div anyway.
If i set state.containerWidth = 1200, yes, rendering fine.

P.S. it`s become from ^6.2.0. Older versions works fine too.

**Comment by neptunian** [comment]
I was able to get this once, then re installed the the gallery and i can't seem to get it anymore.
