### ISSUE TITLE
Max number of rows?

### ISSUE THREAD

**Issue by oyeanuj** [neptunian/react-photo-gallery#110]
Hi @neptunian, thank you for creating this library! I'm curious if there is a way to have a maximum number of rows displayed? 

I've use-cases where I'm showing a preview and would like to show only one or two rows of images initially.

**Comment by neptunian** [comment]
why dont you just limit the number of photos you pass into the gallery initially?  like only pass 10 items into the photos prop and then load more later by adding more items?  you could do that in the component that renders Gallery.  if you run the demo app locally there is a "loading more" example.
