### ISSUE TITLE
Support both lightbox and selection?

### ISSUE THREAD

**Issue by drinksong** [neptunian/react-photo-gallery#114]
In this case, ImageComponent`s onClick prop need extra parameter, so I can handle different callback.

```
  handleClick = (event, { index }, extraParams) => {
    const { photos, onClick } = this.props;
    onClick(event, {
      index,
      photo: photos[index],
      previous: photos[index - 1] || null,
      next: photos[index + 1] || null,
    },  extraParams);
  };
```

Do you have other solutions if no extra parameters?

**Comment by drinksong** [comment]
I hope to receive your reply. : )

**Comment by neptunian** [comment]
you could just call two functions from the one callback.  you can't pass two onClick's to one element so you need to do whatever you need to do in the one callback.
