### ISSUE TITLE
ie 11 major issue with flexbox (Infinite loop with max-width: 100% )

### ISSUE THREAD

**Issue by flexpeace** [neptunian/react-photo-gallery#117]
I have the follow DIV with react-photo-gallery rendered inside 

**CSS**
```
  .main {
    display: flex;
    padding: 20px;
    flex-direction: row;
    flex-wrap: nowrap;
    align-items: stretch;
}


@media (min-width: 200px)
.sub-main {
   max-width:100%; //Looks like this is causing the issue
}

@media (min-width: 1012px)
.sub-main {
    max-width: 550px;
}
```
**HTML rendered by React**
```
<div class="main">
<div class="sub-main">
//----- End of Render by React-photo-library
<div class="react-photo-gallery--gallery">
<div style="display: flex; flex-flow: row wrap;">
<img src="../../../assets/img/no_img.jpg" width="261" height="261" style="margin: 3px;">
<img src="../../../assets/img/no_img.jpg" width="261" height="261" style="margin: 3px;">
<img src="../../../assets/img/no_img.jpg" width="261" height="261" style="margin: 3px;">
<img src="../../../assets/img/no_img.jpg" width="261" height="261" style="margin: 3px;">
</div>
</div>
//----- End of Render by React-photo-library
<div>
</div>
```

**Problems on ie 11:**
1. When the screen has a min-width: 1012px, the library works very well, tested on all major browsers
2. When l reduce ie 11 browser and my CSS  max-width:100% kicks in, l keep seeing the width and height of the images recalculating, entering into infinite loop. And the scrollbar keeps going up and down very crazily. **NOTE:** This only happens when there are 4 or more images 

looks like there is an issue when the library is nested inside a flexbox on ie11

Please could you help me fix this issue?

**Comment by flexpeace** [comment]
I managed to fix the issue by assigning a percentage to the css class ".sub-main" 
The library was then able to get the right widths for the images without entering into infinite loop.

So basically, flex-basis  (e.g. flex-basis: 80%)  or a flex value (eg. flex: 1) is required on the parent element that holds react-photo-gallery else it has a potential of entering into infinite loop

**Comment by mananjadhav** [comment]
Thanks @flexpeace. I faced the same issue on Chrome with MacOS though. Your solution worked for me. 

My issue was if I have 2 rows of images then the grid showed up right. But if I changed the state with filtered elements with only one row of images, it went into an Infinite loop.
