### ISSUE TITLE
There's no possible to change photos via state

### ISSUE THREAD

**Issue by francisrod01** [neptunian/react-photo-gallery#118]
The react-images issue about the examples: https://github.com/jossmac/react-images/issues/266

The photo object is not changing in the `Gallery` component via state.
I created a "folder gallery", a multi gallery component to render a new one if you select it by click.

See the demonstration:
https://codesandbox.io/s/50wr02n8q4

Envs:

* react-photo-gallery: 6.2.2
* react: 16.6.3
* npm: 6.4.1 

https://stackoverflow.com/questions/53472436/react-photo-gallery-dont-change-photos-via-state

**Comment by neptunian** [comment]
if you need help, please use the gitter chat instead of opening issues.

**Comment by francisrod01** [comment]
Here's the repo's gitter chat: https://gitter.im/react-photo-gallery/Lobby
