### ISSUE TITLE
Can't load local images

### ISSUE THREAD

**Issue by LirryPinter** [neptunian/react-photo-gallery#120]
Is it possible to display local images? Because they dont seem to load..

**Comment by neptunian** [comment]
they are image tags with whatever url you pass, so if they aren't loading, then it's something on your end.

**Comment by Zayyad1453** [comment]
@neptunian  Can you provide an example using local images? I have the same issue and I have tried. Can't seem to find any examples online either. 


I tried both of these:
```
  import img1 from './../../../images/img1';

  {src: "./../../src/images/img1", width: 960, height: 300},
  {src: {img1}, width: 960, height: 300},
```

**Comment by Zayyad1453** [comment]
> @neptunian Can you provide an example using local images? I have the same issue and I have tried. Can't seem to find any examples online either.
> 
> I tried both of these:
> 
> ```
>   import img1 from './../../../images/img1';
> 
>   {src: "./../../src/images/img1", width: 960, height: 300},
>   {src: {img1}, width: 960, height: 300},
> ```

I sorted it out. Change

```
 import img1 from './../../../images/img1';
{src: {img1}, width: 960, height: 300},
```
to


```
 import img1 from './../../../images/img1';
{src: img1, width: 960, height: 300},
```

by removing the curly brackets around the image src.
