### ISSUE TITLE
Make it possible to set the gallery wrapper class

### ISSUE THREAD

**Issue by Windvis** [neptunian/react-photo-gallery#122]
The Gallery component's wrapping div has a [hardcoded](https://github.com/neptunian/react-photo-gallery/blob/dfeff66988ec0117582ca58ddcc2e4b9f83dfa5a/src/Gallery.js#L70) `react-photo-gallery--gallery` class. It would be nice if that class was configurable / extendable. Maybe just make that the default?

`<Gallery />` => div.react-photo-gallery--gallery
`<Gallery className="some-class" />` => div.some-class

Thoughts?

**Comment by woss** [comment]
for now wrap it in a div and assign the `className` to the div
