### ISSUE TITLE
Column layout syntax

### ISSUE THREAD

**Issue by LadyCarni** [neptunian/react-photo-gallery#130]
In the demo example for the columns layout, the suggestion is to use the format:
`columns="4"`
But you'll encounter a console error indicating that `columns` is an invalid prop type
Changing the syntax from a string to an integer will fix this:
`columns={4}`

**Comment by neptunian** [comment]
If you read the API documentation, only a number of function is allowed.

**Comment by neptunian** [comment]
Where are you seeing this?

**Comment by LadyCarni** [comment]
Guess it's mysteriously disappeared from the demo in codesandbox ;)

**Comment by neptunian** [comment]
Oh, i was messing with those a lot yesterday so maybe I removed something.
