### ISSUE TITLE
How to prevent re-rendering of Gallery component when we re-render parent component?

### ISSUE THREAD

**Issue by DimaBur** [neptunian/react-photo-gallery#139]
I have structure:

```
class MyComponent extends React.Component() {
	constructor(){
		super();
		this.state = {
			hovered: false,
		}
	}
	render() {
		return(
			<div>
				...component content...
				<Gallery
					photos={photos}
					columns={2}
					ImageComponent={({ ...props }) => (
						<GalleryItem
							{...props}
						/>
					)}
				/>
				...comopnent content...
			</div>
		)
	}
}
```

After I changing state hovered=true/false it causes rerender of <Gallery> - component, and it's re-render looks like glitch. Can I prevent it's re-render?

**Comment by neptunian** [comment]
When you update a parent component's state it will cause the component and all child components to rerender.  So this is normal.  I do have a memoized version I plan to release soon which would stop it rendering in these cases.

**Comment by DimaBur** [comment]
Sorry, how soon are you planning to release memoized version? We are using your component in our project which should be released soon. But we need to fix this gallery behavior. I can fork and enhance your library or wait your update. 
Thank you for this great component!

**Comment by neptunian** [comment]
It's done but there are issues with tests failing due to changing to hooks and I probably won't get around to fixing it anytime soon.

**Comment by neptunian** [comment]
use v8
