### ISSUE TITLE
Two children with the same Key

### ISSUE THREAD

**Issue by 0104910052** [neptunian/react-photo-gallery#141]
Hello, this is a great looking library you did there, I am really happy with the result, but I am getting an error about a duplicate key in my console.

> The error is the following: 
Encountered two children with the same key, `/static/media/2.438e3e4e.jpg`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

I just made an array of images in my state and provided them to the Gallery Component.

`                    <Gallery photos={this.state.photos} />
`

`this.state = {
            photos: [
                {
                    src: img1,
                    width: 5,
                    height: 7
                },
                {
                    src: img2,
                    width: 4,
                    height: 3
                },
                {
                    src: img3,
                    width: 3,
                    height: 2
                },
                {
                    src: img4,
                    width: 3,
                    height: 2
                },
            ]
        }`

am I missing something here?

**Comment by neptunian** [comment]
Unless you provide a "key" attribute, Gallery will use "src" as the default.  You must have 2 repeating images with the same 'src'.  If that is intentional you need to provide your own unique keys.

**Comment by 0104910052** [comment]
Okay, I totally got it, thanks for your quick response, really appreciate it!
