### ISSUE TITLE
Single Row of images can't settle on an image size

### ISSUE THREAD

**Issue by KennyHammerlund** [neptunian/react-photo-gallery#166]
I have the basic implementation set with 12 images with a size of {width: 3, height: 4} 
When they are condensed into a single row the size continually gets smaller as if the size setting function is in a continuous loop

**Comment by mhalle** [comment]
I'm seeing this too. Single rows of justified images will shrink in a loop, then spring back to their original size, and then shrink again.  Latest Safari and Firefox show this problem, Chrome doesn't.

I've been able to work around it, I think. It only happens for me if the gallery is nested in a table, strangely.

**Comment by sammovale** [comment]
Yeah I have also experienced this issue having three images all on the same row. Images are squashed instead of displayed in their normal aspect ratio.

**Comment by oyeanuj** [comment]
@sammovale @KennyHammerlund @mhalle Have you all found a workaround?

@neptunian Any thoughts on what might be going on here?

**Comment by neptunian** [comment]
Yes, I think it's been brought up before and it's a bug.

**Comment by Tugsbayar** [comment]
> I have the basic implementation set with 12 images with a size of {width: 3, height: 4}
> When they are condensed into a single row the size continually gets smaller as if the size setting function is in a continuous loop

It is the problem that I have and pain in my head.  In my case, it keeps looping, shrinking image sizes and auto start over then again shrinking. It usually happens when I have a few images ( 2-5 images) in widescreen. When the container is small, it works fine. If it goes wide, it starts to the loop. But, I have many images (more than 10 ), it works fine.

**Comment by Tugsbayar** [comment]
> I'm seeing this too. Single rows of justified images will shrink in a loop, then spring back to their original size, and then shrink again. Latest Safari and Firefox show this problem, Chrome doesn't.
> 
> I've been able to work around it, I think. It only happens for me if the gallery is nested in a table, strangely.

In my case, the error is persistent in Chrome(version 83.0.4103.106 (Official Build) (64-bit)) and Firefox (version 76.0.1 (64-bit)).

**Comment by dannya** [comment]
Same issue as #157

**Comment by dannya** [comment]
I believe that I've resolved this issue in the above pull request.

**Comment by PaperPlane01** [comment]
@dannya 
> I believe that I've resolved this issue in the above pull request.

Hi, I've tried your fork in my project and unfortunately it didn't help :( It's still keep shrinking in a loop

**Comment by PaperPlane01** [comment]
The only thing that seems to work for me is hard-coding gallery width, as mentioned [here](https://github.com/neptunian/react-photo-gallery/issues/157#issuecomment-562389413). I'm calculating it using the width of parent component which is retrieved via `useRef` hook.
