### ISSUE TITLE
Remove 'resize' event listener when component unmounts.

### ISSUE THREAD

**Issue by Hexrays** [neptunian/react-photo-gallery#2]
I'm using the photo gallery with react router and when I switch from one gallery to the next (swapping out the entire photoset) and then resize the browser I get this error, `Uncaught Invariant Violation: findDOMNode was called on an unmounted component.` The window still seems to be listening for changes on the Gallery that has been removed.

Adding this seems to fix it pretty easily:
```javascript
componentWillUnmount(){
    window.removeEventListener('resize', this.handleResize, false);
}
```

Thanks, this is great!

**Comment by neptunian** [comment]
Thanks! @Hexrays

**Comment by DjordjePetrovic** [comment]
@Hexrays hey! I installed latest version of lib from npm and I'm still getting this error, it looks like this commit is not there, can you deploy it? Thanks

**Comment by neptunian** [comment]
@DjordjePetrovic  Try now?
