### ISSUE TITLE
Bug: Intermittent image quality degradation

### ISSUE THREAD

**Issue by iMerica** [neptunian/react-photo-gallery#21]
Hi 👋 ,

Thanks for building this component - it's super helpful!

**Steps to Reproduce**
- Create a photoset that includes ~8 images from of a common aspect ratio mixed between portrait and landscape modes, include a srcset per image.
- Pass the photoset to the gallery and render it.

**Expected Results**
All images should all display clearly with the original aspect ratio preserved at varying viewport widths.

**Actual Results**
About half the time, the last or second to last image displays blurry on a full width view port (1920x1080). The lightbox image quality always looks good.

If I figure it out why this is happening, I'll submit a PR 😃 .

Thanks,

Michael

**Comment by neptunian** [comment]
@iMerica  I've also noticed this now and again.  I'll look into it, too.  Thanks!

**Comment by neptunian** [comment]
@iMerica  i've noticed this happens to me when the image is in the last row and there arent 3 images.  it could be that the image is not high res enough to deal with the larger size it takes on due to the fact there arent enough images to fill the row.  i should probably prevent this last row resizing the images.

**Comment by neptunian** [comment]
@iMerica  can you tell me if this only happens when an image is in the last row of a gallery?

**Comment by iMerica** [comment]
Yeah that sounds right. From what I recall it affected the last row.

**Comment by neptunian** [comment]
@iMerica  I believe the aspect ratio is still preserved, rather its being stretched too big to fit the whole row so the resolution looks bad.  i think the solution is that in the case when the last row of the gallery has fewer images than the rest, to not stretch it (or them) to fit the whole row but instead have it act as if there are in fact the same amount of images in that row so as to maintain consistency in size with the other images. So there will be whitespace instead.

**Comment by iMerica** [comment]
White space is preferable to image degradation so I think that works 👍 . It would be good to first check if the image width is wide enough to stretch across the viewport width. Otherwise, display full res + white space.

**Comment by neptunian** [comment]
@iMerica that could be something to consider for panorama type images.  but that's been an issue i've always had where i'd like panoramas to be on their own row, but ill think about that later.
