### ISSUE TITLE
Publish 4.2.15 to clear peerDependencies warning

### ISSUE THREAD

**Issue by rpastorelle** [neptunian/react-photo-gallery#24]
Current NPM version is `4.2.14` and throws warnings for `react` & `react-dom` packages for not meeting the following: `peerDependencies: "~15.3.0"`

Looks like you have it fixed in `master`. Please publish a new version.

It may also be helpful to list that as `^15.4.0` so anything above 15.4 works

**Comment by medz** [comment]
I also encountered the same problem.

**Comment by neptunian** [comment]
Published
