### ISSUE TITLE
Thumbnails image size is uncontrolled

### ISSUE THREAD

**Issue by zdrsoft** [neptunian/react-photo-gallery#26]
The thumbnail images size is recalculated, so I could not manage the size of thumbnail images, in this way the size is uncontrolled by json images objects photo set. Please advice. Here is your code for recalculation, why don't you add parameter, which exclude calculation of image size by aspect ratio?
...
        for (var i=0;i<this.props.photos.length;i+=rowLimit){
            var rowItems = [];
            // loop thru each set of rowLimit num
            // eg. if rowLimit is 3 it will  loop thru 0,1,2, then 3,4,5 to perform calculations for the particular set
            var aspectRatio=0,
                totalAr=0,
                commonHeight = 0;
            for (var j=i; j<i+rowLimit; j++){
                if (j == this.props.photos.length){
                    break;
                }
		totalAr += this.props.photos[j].aspectRatio;
            }
            commonHeight = contWidth / totalAr;
            // run thru the same set of items again to give the common height
            for (var k=i; k<i+rowLimit; k++){
                if (k == this.props.photos.length){
                    break;
                }
...
#######################

**Comment by neptunian** [comment]
@zdrsoft  The idea is that the images are responsive.  Depending how many images are in the row it calculates the widths of the images to fill the images container and recalculates if the container width changes.  That's pretty much the main point of the Gallery.  Does that make sense?

**Comment by zdrsoft** [comment]
In the case where I use it, the images are not shown as is expected, the images goes on the next row and are not well sized, even if the images are just 2 or 3. 
Responsive image size could be reached via applying css on the images width: 100%;
    height: auto;. Any way I did fork of the Gallery, reuse the code in my case with some modifications. Thank you.

**Comment by neptunian** [comment]
@zdrsoft image width 100% would not be able to have a certain number of images side by side on the same row, that's why the widths have to be calculated manually and based on their aspect ratio so the height is also the same as the other images in the same row.
