### ISSUE TITLE
Loading... does not work in IE11

### ISSUE THREAD

**Issue by prothomsoft** [neptunian/react-photo-gallery#27]
Please note that loading does not work in IE11.

**Comment by prothomsoft** [comment]
I found reason why it does not work. Fix is as follows:
let scrollY = window.scrollY || window.pageYOffset || document.documentElement.scrollTop;
    if ((window.innerHeight + scrollY) >= (document.body.offsetHeight - 50)) {      
      this.loadMorePhotos();
    }

**Comment by neptunian** [comment]
@prothomsoft  i'll look into this, thanks!
