### ISSUE TITLE
Display images in smaller sizes

### ISSUE THREAD

**Issue by anediaz** [neptunian/react-photo-gallery#28]
Hi,
I want to display images in a smaller size, in order to have more images per line.
I've tried to do so passing by props small photos with small width and height values, but nothing changes, there are always 3 photos per line.

Could you please give me a clue ?

Ane

**Comment by neptunian** [comment]
@anediaz  That is unfortunately built in.  Let me think of a way to pass those in as custom props.  Right now its based on the size of the viewport so a mobile size would get one image per line, a little bigger and you get to and anything more is 3.

**Comment by anediaz** [comment]
Thank you @neptunian !
I'll to try to do it by myself, I'll send you a merge request when it's done ;-)

**Comment by neptunian** [comment]
see issue #32
