### ISSUE TITLE
Preload images

### ISSUE THREAD

**Issue by hakunin** [neptunian/react-photo-gallery#3]
Hi,
I love the small footprint of the gallery.

Have you considered adding a preloader for the next image or two? Thats a must-have for a gallery imo.

**Comment by neptunian** [comment]
@hakunin Thank you the comment.  I'm actually using the react-images component for the "Lightbox" display.  There is currently an issue open: https://github.com/jossmac/react-images/issues/25

**Comment by neptunian** [comment]
@hakunin  this has been implemented https://github.com/jossmac/react-images/issues/25
