### ISSUE TITLE
Custom filters extending the PHOTO_SET

### ISSUE THREAD

**Issue by yuripramos** [neptunian/react-photo-gallery#38]
Is it possible? I would like to create my own filters in the gallery, to display only images according to the user wish.

**Comment by neptunian** [comment]
are you talking about a search, like searching through image tags?

**Comment by yuripramos** [comment]
Yes, this.

Em 10/02/2017 13:03, "Sandra" <notifications@github.com> escreveu:

are you talking about a search, like searching through image tags?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/neptunian/react-photo-gallery/issues/38#issuecomment-278968160>,
or mute the thread

**Comment by neptunian** [comment]
@yuripramos I don't see why not, but I don't think it needs to be built into this Gallery.  What would you need from me in order to get that working for you?

**Comment by neptunian** [comment]
@yuripramos wouldnt you filter the images you want BEFORE passing it to the Gallery component?  Don't pass anything to the PHOTO_SET you do not want to be there.
