### ISSUE TITLE
Option for custom number of images per row

### ISSUE THREAD

**Issue by neptunian** [neptunian/react-photo-gallery#40]
See issue #32

**Comment by neptunian** [comment]
@smeijer can you review my changes and let me know what you think?  thanks

**Comment by smeijer** [comment]
I see the issue is closed. Still want feedback?

**Comment by neptunian** [comment]
@smeijer  yes please.  i figure the user can use measureit however they want in the app file.

**Comment by smeijer** [comment]
Before I start bashing 😋 , what code do you want me to take a look at? There is no PR is there? Or do you simply mean the master branch? Specific commit perhaps?

**Comment by neptunian** [comment]
@smeijer Sorry, I'll be better at creating PRs :)
https://github.com/neptunian/react-photo-gallery/commit/85b9ac7e30e7a9e8e2a29c85834dd1a6232dfc0d

**Comment by smeijer** [comment]
@neptunian, looks great 👍
