### ISSUE TITLE
Image alignment issue

### ISSUE THREAD

**Issue by iMerica** [neptunian/react-photo-gallery#42]
Hi,

I'm not seeing this issue on your gallery, but it's definitely showing up consistently on my side. See below

![photo-gallery-issue](https://cloud.githubusercontent.com/assets/487897/23338632/e04d1cf8-fbc4-11e6-8f25-4e3b939849b4.png)

On the last row, the image doesn't appear to be fill 100% of the container width. In my particular case, the `containerWidth` is 1280, but the inline style width is being set to `1266`.

**Comment by neptunian** [comment]
This is also in the last row right?  The calculation is incorrect because its still taking margin into consideration.  I think i actually fixed this with one of my latest commits to add 'cols' options.

**Comment by iMerica** [comment]
Yes, this is the last row. I updated inline in my web inspector and it looks like in order to have gotten in perfectly, it would beed to be `1272`.

**Comment by iMerica** [comment]
It looks like it only happens when there is only one image on the last row.
