### ISSUE TITLE
Cols property does't work

### ISSUE THREAD

**Issue by koltyakov** [neptunian/react-photo-gallery#47]
Hi there,

First off, thanks for the component. I'm new to it, yet it seems to be a nice solution for one of the tasks.

During first steps experiments, I found out that `cols` property doesn't work as if it were ignored at all.
After digging down to `lib/Gallery.js` and `render()` method I can see why, generated script uses hardcoded `rowLimit`:

```javascript
var rowLimit = 1, 
    photoPreviewNodes = [];
if (this.state.containerWidth >= 480) {
  rowLimit = 2;
}
if (this.state.containerWidth >= 1024) {
  rowLimit = 3;
}
```

but not the value from the property as it should due to the documentation and original script part:

```javascript
var cols = this.props.cols,
    photoPreviewNodes = [];
if (!this.props.cols){
  cols = 3;
}
```

My guess that it's an artifact of some previous version and in the Repo is an old `lib/Gallery.js` which is a main script in the NPM module.

Can something be done with it in next version bump?

Cheers,
Andrew

**Comment by neptunian** [comment]
@koltyakov Thanks, I will push the right version in an hour or so with another bug fix.

**Comment by neptunian** [comment]
@koltyakov  should be good now

**Comment by koltyakov** [comment]
Now it works. Thank you Sandra!
