### ISSUE TITLE
Grid is broken in version 5.3.0 on NPM

### ISSUE THREAD

**Issue by iMerica** [neptunian/react-photo-gallery#48]
### Issue
Hi Sandra,

I just upgraded from `5.0.2"` to `^5.2.0"` on NPM and noticed that the grid is now broken.  

Here's what it looks like using random images on Unsplash.

![bug](https://cloud.githubusercontent.com/assets/487897/23818417/90e02cf6-05af-11e7-85d3-f005fdcf9628.png)

After downgrading to `  "react-photo-gallery": "5.0.2",`, the images look back to normal:

![screen shot 2017-03-10 at 4 50 11 pm](https://cloud.githubusercontent.com/assets/487897/23818620/b57d1194-05b1-11e7-895f-4185206ef6be.png)

Secondarily, the versions on Github don't sync with the versions on NPM making this issue a bit more difficult to bisect/debug.

### Info
`$ cat node_modules/react-photo-gallery/package.json | grep gitHead`
> "gitHead": "51613a4ef2da6c5885e9027abc85a9aea0cd1e42",

**Comment by neptunian** [comment]
@iMerica  i just did an npm install and ran the example app and it all seems to be working okay.  does the example app work for you?

**Comment by iMerica** [comment]
Hmm sounds like maybe there was an API change that doesn't play nice with the previous version.

**Comment by neptunian** [comment]
@iMerica you are right, i should have changed the version number.  It's probably the new 'margin' property?  although it shouldn't be...  its broken at any browser width or a certain one?

**Comment by iMerica** [comment]
I'm still debugging it, but it does appear to be a math problem with how the widths are now calculated.

Issue(s):

Case: Single photo
Results: The image displays on about 1/3rd of the space available.

Case: 2 Photos, large/wide browser width:
Results: The images display side by side, but do not take up the entire container width.

Case: 3+ photos
Results: Images display erratically.

I think theres a mixed message being sent by the README and the Example app (or maybe I'm misreading something). The README tells me I can pass an array of photo objects that are of varying dimensions and `react-photo-gallery` will figure out how to maintain the aspect ratio and use all the available space of the container to create a nice looking collage

The example app uses the [measure](https://github.com/souporserious/react-measure) component **outside** of `react-photo-gallery` which tells me it's the user's responsibility to calculate the widths and columns, no the responsibility of `react-photo-gallery`.

**Comment by neptunian** [comment]
@iMerica yes it is now the user's responsibility to handle the columns.  it defaults to 3 so if you dont pass in cols it should still work but always only have 3.  This is because many people requested wanting to pass in their own # of cols instead of me having it fixed and hardcoded in Gallery.js

https://github.com/neptunian/react-photo-gallery/issues/32

**Comment by iMerica** [comment]
Yep, using Chrome

**Comment by neptunian** [comment]
@iMerica  btw you are not actually calculating any widths.  the Measure module is just what someone might want to use to detect the width of their own app and decide how many columns they want based on that width.  the user can use whatever they want to figure this out, but i think the user should be able to control the # of cols based on whatever width they see fit.

**Comment by iMerica** [comment]
I was able to workaround this bug by forcing the left/right margin of the parent div to be zero.

For example, my markup looks like this:

```jsx
<div className="row">
    <Gallery ... />           
</div>
```

and the styles for `row` (using Materialize, a popular CSS framework) were:

```css
.container .row {
    margin-left: -0.75rem;
    margin-right: -0.75rem;
}
```

The previous version of react-photo-gallery played nice with parent divs having their own margin left/right, but this current version uses margin and doesn't factor in the margin that already exists of the parent div. The reason you don't see this on your example app is because you have no margin on your example app's parent div.


Possible fixes: 

- Add a warning to the README that the parent div can't have any margin 😃 . 
- Offset the total combined width by the parent div's margin.
- Only apply a margin to the sides that are facing inwards (might be kinda tough)

**Comment by neptunian** [comment]
@iMerica hmm let me look into this.  thanks.

**Comment by neptunian** [comment]
@iMerica  i added both padding and margin to the Gallery's parent div and the div above that and did not see any problems.  

<img width="1108" alt="screen shot 2017-03-13 at 9 55 08 am" src="https://cloud.githubusercontent.com/assets/1676003/23865630/883bef10-07d3-11e7-8a68-5bc11cef65d3.png">
