### ISSUE TITLE
Compatibility issue with react-images 0.3.3

### ISSUE THREAD

**Issue by ohtake** [neptunian/react-photo-gallery#5]
react-photo-gallery 4.2.4 depends on react-images "^0.3.2".
Since react-images has released 0.3.3, react-photo-gallery will use react-images 0.3.3 and give an error.

> ReactTransitionGroup: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)

Either of the followings will resolve the issue.

1. Explicitly use react-images 0.3.2, not 0.3.3.
2. Update react-images to 0.4.x and update react & react-dom to 15.x.

**Comment by neptunian** [comment]
@ohtake  Sorry for the late response.  I opened up an issue with react-images.  It seems there are also issues with 0.4.6 https://github.com/jossmac/react-images/issues/48 .  I'm going to explicitly set the version to 0.3.2 for now.
