### ISSUE TITLE
<a> class name set to image index

### ISSUE THREAD

**Issue by jorrit** [neptunian/react-photo-gallery#55]
Gallery.js contains `<a href="#" className={k} onClick={(e) => this.props.onClickPhoto(k, e)}>`. This leads to the following HTML (from the example page):

```html
<a href="#" class="1">...</a>
```

I was wondering if the numeric class name is intended or a side effect of something different.

**Comment by neptunian** [comment]
@jorrit i don't know why that's there and i'm pretty sure it isn't needed.  i should probably remove it.

**Comment by jorrit** [comment]
Thanks. I also noticed that the gallery `<div>` has fixed `id` and `class` attributes. Could you also remove those?

**Comment by neptunian** [comment]
@jorrit this was addressed with recent new version although there is a class on the Gallery
