### ISSUE TITLE
Unknown props `photos`

### ISSUE THREAD

**Issue by vivekiyer114** [neptunian/react-photo-gallery#56]
I am getting this error in console 

`proxyConsole.js:56 Warning: Unknown prop `photos` on <gallery> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in gallery (at gallery.jsx:7)
    in Gallery (created by RouterContext)
    in RouterContext (created by Router)
    in Router (at routes.js:8)`

**Comment by vivekiyer114** [comment]
My code 

`import React from 'react';
import {Gallery as gallery} from 'react-photo-gallery';

class Gallery extends React.Component{
	render (){
		return (
				<gallery photos={PHOTO_SET} />
			);
		}
	}

export default Gallery ;

const PHOTO_SET = [
	{src:'../assets/1.jpg'}
]`

**Comment by vivekiyer114** [comment]
import React from 'react';
import {Gallery as gallery} from 'react-photo-gallery';

class Gallery extends React.Component{
	render (){
		return (
				<gallery photos={PHOTO_SET} />
			);
		}
	}

export default Gallery ;

const PHOTO_SET = [
	{src:'../assets/1.jpg'}
]

**Comment by vivekiyer114** [comment]
import React from 'react';
import {Gallery as gallery} from 'react-photo-gallery';

class Gallery extends React.Component{
	render (){
		return (
			&lt; gallery photos={PHOTO_SET}  />
			);
		}
	}

export default Gallery ;

const PHOTO_SET = [
	{src:'../assets/1.jpg'}
]

**Comment by neptunian** [comment]
@vivekiyer114 are you able to run the demo locally without errors?

**Comment by vivekiyer114** [comment]
No.
The photos are not showing up at all , because the main warning is in the prop `photos` itself .

**Comment by neptunian** [comment]
i just tested the component by installing from NPM and following the instructions and there were no errors and the component is functioning.  unfortunately, i can't help you without more info.

**Comment by vivekiyer114** [comment]
Okay i will reproduce the problem. 
Let me know if we can connect through teamviewer so that you can sort it.

Thank you !
