### ISSUE TITLE
When used with lightbox, calculated sizes give broken layout

### ISSUE THREAD

**Issue by benjamintd** [neptunian/react-photo-gallery#59]
On Windows machines, the scrollbar is 17px wide.

This scrollbar disappears when the Lightbox is opened. Then, a re-render of the Gallery is triggered when the Lightbox is closed. At this time, `this._gallery.clientWidth` is 17px wider than when first rendered. The computed widths for all pictures is therefore bigger.

However the scrollbar comes back afterwards, which forces the images to go into subsequent rows and break the layout.

I solved this issue by adding the following lines to my CSS:

```css
html {
        overflow-y: scroll;
      }
```

which causes the scrollbar to be always visible, and therefore the `clientWidth` of the gallery to be constant.

I notice that in the demo, `body` has a padding of 17px (width of a scrollbar), is that for this reason? 

How could this issue be solved at the component level?

Thanks for your package, it's been really helpful!

**Comment by neptunian** [comment]
@benjamintd try updating the react-scrolllock dependency, bug was introduced in it that should be fixed now.

**Comment by neptunian** [comment]
@benjamintd a new version of react-scrolllock was just released that should fix the issue.

**Comment by mleister97** [comment]
Still having the same issue
