### ISSUE TITLE
srcset and sizes are no longer optional

### ISSUE THREAD

**Issue by littletower** [neptunian/react-photo-gallery#67]
In 6.5.3, the properties ```srcset``` and ```sizes``` are no longer optional, if they are not set, you get an ```undefined``` error.

**Comment by neptunian** [comment]
not sure what version '6.5.3' you are referring to.  I just tested the app by removing these props and there was no issue.

**Comment by littletower** [comment]
well this is weird... I upgraded to 6.0 now anyway and it works great! Thanks for your quick reply and this awesome photo gallery
