### ISSUE TITLE
Can't resolve 'react-measure'

### ISSUE THREAD

**Issue by voodooattack** [neptunian/react-photo-gallery#68]
Just updated to 6.0.0, getting this error from webpack:
```
Warning: Module not found: Error: Can't resolve 'react-measure' in '/dist/node_modules/react-photo-gallery/lib'

Aborted due to warnings.
```

**Comment by neptunian** [comment]
@voodooattack hmm did you try doing an npm install again?  see what your react-measure version is.  It should be  "react-measure": "^2.0.2"

**Comment by SuttJ** [comment]
Having this same issue. I have react-measure version 2.0.2

**Comment by neptunian** [comment]
@SuttJ are you also using webpack?

**Comment by neptunian** [comment]
@SuttJ @voodooattack sorry i left something in i was no longer using in the gallery.  published new version to npm.
