### ISSUE TITLE
documentation is not matching real code requirements

### ISSUE THREAD

**Issue by rokyed** [neptunian/react-photo-gallery#69]
documentation is not matching real code requirements

**Comment by neptunian** [comment]
@rokyed care to say where?  not very helpful comment.

**Comment by rokyed** [comment]
sorry for being pretty mean, when i wrote this, i was very cranky.

but the bug is: if you don't provide srcset: [] (optional) the gallery will shoot errors :) i hope it helps.

**Comment by neptunian** [comment]
i am not able to reproduce an error when not including the srcset property in the photo object.
