### ISSUE TITLE
"srcset" and "sizes" are marked as optional, but cause "undefined" error when missing

### ISSUE THREAD

**Issue by ajhool** [neptunian/react-photo-gallery#70]
This error seems to have been introduced in one of the recent commits.

My code has not changed, but has started to fail with the following error:

```
Cannot read property 'join' of undefined
    at Gallery.js:135
    at Array.map (<anonymous>)
    at Gallery.render (Gallery.js:126)
```

Line 135 of Gallery (runtime, after compile):
`_react2['default'].createElement('img', { src: photo.src, srcSet: photo.srcset.join(), sizes: photo.sizes.join(), style: { display: 'block', border: 0 }, height: photo.height, width: photo.width, alt: photo.alt })
`

I wasn't able to find the issue in the code (it might be a srcset vs srcSet thing), but was impressed by how clean your code is!

A quick patch is to pass srcset=[] sizes=[] as props to the gallery component

**Comment by neptunian** [comment]
you are right, it should by srcSet.  i updated the README and release notes.  thanks for the catch!
