### ISSUE TITLE
onLoad componentShouldMount Warning 

### ISSUE THREAD

**Issue by kylefoley** [neptunian/react-photo-gallery#72]
Not causing any issues that I can see, just wanted to bring it to your attention. When I load my child that contains Photo Gallery, I get this error - 

`Gallery has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extend React.Component if shouldComponentUpdate is used.`

Only started happening when I upgraded to React 16.

Thanks!

**Comment by neptunian** [comment]
@kylefoley thanks i will push a release later today

**Comment by kylefoley** [comment]
Great, thanks for the quick response

**Comment by neptunian** [comment]
This should be fixed in 6.0.7
