### ISSUE TITLE
Photos not displaying

### ISSUE THREAD

**Issue by kylefoley** [neptunian/react-photo-gallery#73]
Upgraded to v. 6.0.7, photos no longer display when added to a photo array. I downgraded to 6.0.1 and it began working again. Not getting any errors in the console. React 16.0.0

**Comment by neptunian** [comment]
are you able to run the example?

**Comment by kylefoley** [comment]
Yes, the examples at http://neptunian.github.io/react-photo-gallery/ work perfect

**Comment by kylefoley** [comment]
Testing the one that came in the npm package now

**Comment by kylefoley** [comment]
They are working fine as well. Did anything change in regards to adding photos to an array?

**Comment by neptunian** [comment]
no nothing was changed

**Comment by kylefoley** [comment]
Hmm, it is working now. I may have just had to restart my IDE. Thank you @neptunian
