### ISSUE TITLE
Gallery must unmount, then remount to display photos individually added to array

### ISSUE THREAD

**Issue by kylefoley** [neptunian/react-photo-gallery#74]
Hi! I found out how to replicate this issue I was having yesterday. When a user adds a photo to the photo array, Gallery must be unmounted and then be remounted for it to be displayed.

 I can see the photo being added to the array, but Gallery will not display it until it is unmounted and remounted.

It was working on the previous verison of Gallery, not sure what happened to change it. 

React 16.0.0

Thanks!

**Comment by neptunian** [comment]
Hmm i see, okay i'll look into it, thanks for the info.

**Comment by neptunian** [comment]
@kylefoley are you talking about when you dynamically add more photos your images array?

**Comment by kylefoley** [comment]
That is correct. Essentially a user can upload an image and it'll be pushed to S3, as well as displayed in Gallery. For each new photo, I just do a `photoArray.push`, which is the array specified in the `<Gallery>` component

**Comment by neptunian** [comment]
i tested this with the demo and there doesnt seem to be problem.  what i'm doing is as the user scrolls the page i add more photos to the photos array which is stored as a state property.  i'll upload the new example to the demo page.
