### ISSUE TITLE
Receive this error when I try to install the package

### ISSUE THREAD

**Issue by varunsikka** [neptunian/react-photo-gallery#75]
npm install --save react-photo-gallery                                   
npm WARN yourdocabroad-app-react@0.0.1 No repository field.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/varunsikka/.npm/_logs/2017-10-12T17_41_16_230Z-debug.log

I am using NPM 5.3.0

**Comment by varunsikka** [comment]
Update: I upgraded my NPM from 5.3.0 to 5.4.2 and still gives same error. But when I downgrade to NPM 5.2.0 it works

**Comment by neptunian** [comment]
what is this: (dev✱)

**Comment by varunsikka** [comment]
(dev✱) - I copied from my terminal - so this was copied as well. dev is the current branch of my project repo.

**Comment by neptunian** [comment]
cannot reproduce in 5.4.2.  make sure you run `npm init` first and your directory has the proper serttings.
