### ISSUE TITLE
Warning: Unknown DOM property srcset. Did you mean srcSet?

### ISSUE THREAD

**Issue by Xepe** [neptunian/react-photo-gallery#76]
Hello, 
I am using 
"react-photo-gallery": "6.0.15",        
"react-images": "0.5.11",  

When I close the Lightbox I got the following error

![image](https://user-images.githubusercontent.com/2806076/32241666-61efb9b2-be36-11e7-834e-51ce0058fb6d.png)

Regards

**Comment by neptunian** [comment]
are you passing in srcset or srcSet?

**Comment by Xepe** [comment]
I am using srcSet

**Comment by louisdvs** [comment]
I am getting the same issue after updating to the latest version of "react-photo-gallery": "6.0.15".

I changed srcset to srcSet in my images array but still get the error.

Below is the code I use to dynamically generate my image array.

```
export const PHOTO_SET = Object.keys(images).map(function (k) {
        return { src: images[k],
                srcSet: [
        ],
        sizes:[
          '(min-width: 480px) 50vw',
          '(min-width: 1024px) 33.3vw',
          '100vw'
        ],
        width: 627,
        height: 400,
        alt: 'image 1',};
    });


```

**Comment by neptunian** [comment]
just tested using the two components with create-react-app and not getting that warning but i am getting this one:

Expected `onClick` listener to be a function, instead got a value of `boolean` type.

will continue poking around..

**Comment by neptunian** [comment]
i've been able to reproduce this but only when i open the lightbox and then click the next arrow.  after i close it and click around i can't get it again.  @louisdvs do you also only get it when closing?

**Comment by louisdvs** [comment]
Yeah same for me. I get the warning on any action after opening the lightbox (close, prev, next).

**Comment by neptunian** [comment]
this react-images release should fix the issue: https://github.com/jossmac/react-images/releases/tag/0.5.13
