### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by dcurletti** [neptunian/react-photo-gallery#78]
Hi there- Just grabbed this package and placed it in my SSR app and noticed that it pops when SSRed.  I haven't looked at the internals of the package yet, but I'm assuming it requires knowledge of the browser dimensions to work without popping (changing the dimensions of the images)?

Thanks!

**Comment by neptunian** [comment]
what do you mean popping?  and yes it needs to know its container width in order to calculate what size the images should be.

**Comment by neptunian** [comment]
i just tested this on the server and didn't see any kind of popping.
