### ISSUE TITLE
Maximum update depth exceeded

### ISSUE THREAD

**Issue by ghost** [neptunian/react-photo-gallery#81]
While playing with one of your codesandbox example(https://codesandbox.io/s/o7o241q09), I noticed these errors:

![capture](https://user-images.githubusercontent.com/35967083/36611079-b9d241ee-18eb-11e8-8780-cbe5024a73b8.PNG)

Unfortunately  can't recall the exact circumstance when/how this occurred, all I have is this screenshot. Are maintainers aware of this problem?

---
I think I managed to recreate this, it happens when I click "Align To Right", "Align To Bottom" buttons from codesandbox, i.e. these:

![capture1](https://user-images.githubusercontent.com/35967083/36611402-bb04ffc4-18ec-11e8-84a6-143abc8ef659.PNG)

I think it also happens when you try to manually change the size of the window where the preview of the app is shown.

Here is also more info on error:

> 
> Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
>     at invariant (invariant.js:42)
>     at scheduleUpdateImpl (react-dom.development.js:13134)
>     at scheduleUpdate (react-dom.development.js:13124)
>     at Object.enqueueSetState (react-dom.development.js:9646)
>     at Gallery.ReactComponent.setState (react.development.js:218)
>     at Gallery.componentDidUpdate (Gallery.js:57)
>     at commitLifeCycles (react-dom.development.js:11517)
>     at commitAllLifeCycles (react-dom.development.js:12294)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
>     at invokeGuardedCallback (react-dom.development.js:1195)
>     at commitAllWork (react-dom.development.js:12415)
>     at workLoop (react-dom.development.js:12687)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
>     at invokeGuardedCallback (react-dom.development.js:1195)
>     at performWork (react-dom.development.js:12800)
>     at scheduleUpdateImpl (react-dom.development.js:13185)
>     at scheduleUpdate (react-dom.development.js:13124)
>     at Object.enqueueSetState (react-dom.development.js:9646)
>     at Gallery.ReactComponent.setState (react.development.js:218)
>     at Gallery.handleResize (Gallery.js:73)

**Comment by neptunian** [comment]
I'll look into this.. i think i need to debounce the window resizing method

**Comment by giorgim** [comment]
@neptunian please let me know when you fix it.

**Comment by giorgim** [comment]
@neptunian btw. in that same codesandbox example I see you are directly modifying react state:
  ```
  let photos = this.state.photos;
  photos[obj.index].selected = !photos[obj.index].selected;
  
```
which I think is against react best practice: https://reactjs.org/docs/state-and-lifecycle.html#do-not-modify-state-directly

**Comment by neptunian** [comment]
@ghost are you still getting this?  which browser?  I can't seem to recreate it given your directions.
