### ISSUE TITLE
Fluid gallery and dynamic column amount per row

### ISSUE THREAD

**Issue by alamchrstn** [neptunian/react-photo-gallery#84]
Hi, is it possible to support fluid gallery? And instead of setting a fixed number of images per row, is it possible to automatically place images in their place so that there will be no oversized images?
Thanks in advance

**Comment by neptunian** [comment]
its not fixed necessarily.  you can change the number of images per row based on media query.  that's something the user controls and not the gallery so if you want to automate that, you will have to write it.  the Gallery needs to know that information however or it can't calculate the aspect ratio give the row width.
