### ISSUE TITLE
Another -> Uncaught Error: Maximum update depth exceeded

### ISSUE THREAD

**Issue by gerasimoff** [neptunian/react-photo-gallery#86]
In my application I needed to create an album with one picture ( album cover ) but I came across this issue

![2018-04-12_20-26-42](https://user-images.githubusercontent.com/34865609/38690931-69833aa2-3e90-11e8-9c64-57a307f8db48.png)

This error appears when the number of uploaded images is **equal** or **less than the number of columns in the code** (_3 by default_)
`<Gallery photos={photos} onClick={this.openLightbox} columns={2}/>`
as long as I upload more than..say 2....or 3..more than I indicated in `columns={2}`....
everything works perfectly well again
![2018-04-12_20-25-29](https://user-images.githubusercontent.com/34865609/38691330-9b998194-3e91-11e8-8aa8-1fb39b601359.png)

**Comment by neptunian** [comment]
do you get it when resizing the window?

**Comment by gerasimoff** [comment]
No...I did not even touch the window...

**Comment by vtyrtov** [comment]
iframe app on Windows (Chrome or Firefox) scrolling -> scrollbar blinked -> resizeWindow call -> and crash

**Comment by vtyrtov** [comment]
my fix:

`
import Gallery from 'react-photo-gallery'

class Gallery2 extends Gallery {
  handleResize(e) {
    // nothing
  }
  componentDidUpdate() {
    // nothing
  }	
}
`

**Comment by neptunian** [comment]
@gerasimoff am not able to reproduce this 
<img width="1263" alt="screen shot 2018-04-17 at 11 07 33 am" src="https://user-images.githubusercontent.com/1676003/38863480-aa70147a-422f-11e8-894d-6bcc07030d16.png">

**Comment by vtyrtov** [comment]
@neptunian bugs only on Windows (Chrome/Firefox), on MacOS all right...

**Comment by neptunian** [comment]
@vtyrtov try the latest version?

**Comment by vtyrtov** [comment]
@neptunian, using the latest version

```
  handleResize(e) {
    this.setState({ containerWidth: Math.floor(this._gallery.clientWidth) });
  }
```

Dynamic adjustment under the iframe scroll size on Windows leads to a frequent event "resize" and crash (in my case).

**Comment by vtyrtov** [comment]
On the Mac this is not a problem (as there is a scrollbar is displayed only when a user action)

**Comment by neptunian** [comment]
@vtyrtov i'm not getting it on windows 10 chrome.

**Comment by vtyrtov** [comment]
See [video](https://www.dropbox.com/s/7q3yucluxgj58ap/gallery.mov?dl=0)

I think handleResize should do this.setState only if there have been significant changes in _gallery.clientWidth relative to the previous containerWidth.

**Comment by neptunian** [comment]
if its even 1 pixel off it can throw off the layout.  there could be something in your app causing the resize event to trigger too much as i cant reproduce it.

**Comment by vtyrtov** [comment]
I checked. Add in handleResize solves the problem (by analogy componentDidUpdate)
```
  handleResize(e) {
      if (this._gallery.clientWidth !== this.state.containerWidth) {
        this.setState({ containerWidth: Math.floor(this._gallery.clientWidth) });
      }
  }
```
