### ISSUE TITLE
pass props to custom ImageComponent

### ISSUE THREAD

**Issue by scottbarrow** [neptunian/react-photo-gallery#88]
Im passing a custom `ImageComponent` prop to the `Gallery`, is it possible to send props to the `ImageComponent` ?
Thanks

**Comment by neptunian** [comment]
I'm thinking to refactor this bit.  ImageComponent would no longer be a default component that Gallery calls if you don't pass in the ImageComponent prop.  Instead you would import it from the library like: `import Gallery, {ImageComponent} from 'react-photo-gallery'`.  Then it would be passed in using '[render props](https://reactjs.org/docs/render-props.html)' and also pass through any properties you've set on it. You can import ImageComponent from the library or pass in your own.

**Comment by neptunian** [comment]
@scottbarrow I was able to do what you want without having to make changes to the component using partial application.  Have you tried something like this? 
<img width="1023" alt="screen shot 2018-05-28 at 6 55 17 pm" src="https://user-images.githubusercontent.com/1676003/40623769-d7c37ba8-62a8-11e8-9cf9-33b6a9479280.png">

**Comment by neptunian** [comment]
you should be able to achieve this by passing in a function that returns the component:

`<Gallery photos={this.state.photos} columns={this.props.columns} onClick={this.selectPhoto} ImageComponent={({...props}) => <SelectedImage {...props} test={'hi'}/>}/>`

pass along a prop like "test" and retrieve within your component

**Comment by scottbarrow** [comment]
Perfect, thanks
