### ISSUE TITLE
Gallery renders incorrectly when scrollbars are present when first loading

### ISSUE THREAD

**Issue by lpil** [neptunian/react-photo-gallery#89]
Hello! See the screenshot for an example of the problem.

Resizing the window after the first render fixes the problem.

![2018-05-09-221041_870x1051_scrot](https://user-images.githubusercontent.com/6134406/39840005-e60276b0-53d5-11e8-9683-6d82cb01fed3.png)

**Comment by bvv218** [comment]
@lpil Having the same problem. Did you find solution for this?

**Comment by lpil** [comment]
I force the scroll bars to always be on so when the component initialises it detects the correct width

**Comment by rjptl96** [comment]
thanks @lpil. This fixed it!

**Comment by neptunian** [comment]
i'll look into a better fix, thanks!

**Comment by neptunian** [comment]
Does this happen for you when loading the example app? I can't seem to reproduce.

**Comment by lpil** [comment]
It happens when there are no scrollbars when the component initialises, but then scrollbars are added when the images load as it extends the page.

Having it recalculate width onload of each image would do the trick.

**Comment by neptunian** [comment]
are you on windows?  it works fine in this scenario for me.

**Comment by neptunian** [comment]
Chrome seems to overlay a scrollbar so the width doesn't change.

**Comment by lpil** [comment]
It depends on how your window manager renders scroll bars. I suspect OSX uses zero width ones so the width doesn't change when they are added. On Windows, ChromeOS, and most flavours of Linux this will be a problem.

**Comment by neptunian** [comment]
@lpil please see the referenced commit and tell me what you think.  this bug was introduced because of https://github.com/neptunian/react-photo-gallery/issues/86

**Comment by lpil** [comment]
Looks like it would do the trick, but would it be possible to only do this on load and resize rather than on every frame?

**Comment by lpil** [comment]
It registers a callback with `requestAnimationFrame`. This will (perhaps) 60 times a second until the page is refreshed/closed.

**Comment by neptunian** [comment]
yes, when called recursively.

**Comment by lpil** [comment]
Doh, of course! I'm very silly :)

**Comment by neptunian** [comment]
raf seems to wait for the current rendering to finish before its called so it seems to work.   i  tested it through chrome dev tools on slow 3g and it still worked.  woo hoo!
