### ISSUE TITLE
Combination of sort and selection (onClick) possible?

### ISSUE THREAD

**Issue by Fuchssystems** [neptunian/react-photo-gallery#91]
Tried to combine the 2 featured examples:
- SortablePhoto
- SelectImage

I managed to pass an onClick handler to the example "SelectImage"):

`const SortableGallery = SortableContainer(({photos}) => {
  return <Gallery photos={photos} ImageComponent={SortablePhoto}/>
});
`

changed to by adding the propertie 'onClick':

`const SortableGallery = SortableContainer(({photos,onClick}) => {
  return <Gallery photos={photos} onClick={onClick} ImageComponent={SortablePhoto}/>
});`

Option "pressDelay" is used to get an onClick event fired.

However, in SelectedImage this properties are not available: index and photo (the onClick funtion passed has the the 2 parameters index and photo not available because the are not passed to the component).

Any ideas (is it possible at all) to combine the 2 features (selection and sort)?

Best regards

**Comment by Fuchssystems** [comment]
The HOC (Higher Order Component) https://github.com/clauderic/react-sortable-hoc that is used to sort explains in the FAQ that:
"Wrapper props not passed down to wrapped Component
All props for SortableContainer and SortableElement listed above are intentionally consumed by the wrapper component and are not passed down to the wrapped component. To make them available pass down the desired prop again with a different name. "

This explains why the index property is not passed to the component "SortablePhoto" (the child elements of "SortableGallery".

Maybe a workaround would be to pass a second index property (index2) that could be passed to "onClick" in "SortablePhoto" (because the HOC does not pass a property with name "index").

Goal is that a short click selects/deselects, while holding/touching more than 200 ms and dragging sorts.

**Comment by neptunian** [comment]
I think the change I'm suggesting here would solve the problem: https://github.com/neptunian/react-photo-gallery/issues/88  .  Then you could pass in your own props again.

**Comment by Fuchssystems** [comment]
Good idea.

Meanwhile I did a mode toggle ("select" or "sort") to choose between either "click to select" or "drag to sort".
Both modes have instant feedback, however I am not sure if it is "better" for a user to choose modes or "click" or "hold and wait" to drag.
Having to click/press and than wait 200 ms to be able to drag is not very intuitive, however some applications work this way.

Really not sure about the the "right way" to implement "click to select" and "drag to sort"-

Thanks for looking into this.

**Comment by neptunian** [comment]
If you edit a Google Photos photo album they seem to have implemented the ability to delete/select/drag. It seems as soon as you click something and begin to drag it works.

**Comment by neptunian** [comment]
It sounds like you can use any of these solutions to solve your problem: https://github.com/clauderic/react-sortable-hoc#click-events-being-swallowed

**Comment by Fuchssystems** [comment]
Yes. Looks like it should be possible to pass down the properties "photo" and "index".
Think I tried but maybe forgot to pass the properties to "SortableItem".

Thanks for the hint.
Am busy on other topics and will come back to this soon.

**Comment by neptunian** [comment]
also i was able to pass in new properties using partial application if you see the screenshot in #88.  would that solve your problem?

**Comment by prayashm97** [comment]
hi @Fuchssystems were you able to get this working, if so could you help me out, im stuck where the onClick method isn't receiving the index of the image

**Comment by RZhosan** [comment]
Hi @prayashm97.
I think you can use this approach:
https://codesandbox.io/s/xpml0zmv0o

**Comment by Fluorz** [comment]
+1
