### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by pieterclaerhout** [neptunian/react-photo-gallery#94]
Is there a way to do lazy loading for large gallery pages?

By that, I mean it would only load the images which are in the viewport  of the browser?

**Comment by neptunian** [comment]
if you download and run the demo, there is an example for dynamic loading

**Comment by hexadeciman** [comment]
The demo shows an example of using infinite scrolling not lazy loading.

Lazy loading means all the containers for the images are in the dom, but the image is actually fetched only when user scrolls and is in the viewport.

**Comment by ericjanto** [comment]
> The demo shows an example of using infinite scrolling not lazy loading.
> 
> Lazy loading means all the containers for the images are in the dom, but the image is actually fetched only when user scrolls and is in the viewport.

I'm confused; isn't this exactly what's happening in `ExampleDynamicLoading`? I might be mistaken but when watching the Network tab in the Chrome dev tools, images are only fetched and loaded when the user is scrolling them into view.
