### ISSUE TITLE
Not able to remove image

### ISSUE THREAD

**Issue by Olivr3** [neptunian/react-photo-gallery#97]
Hi!

I am not sure if this is a bug or a missing feature. 

It would be nice if we could remove a specific image from the Gallery. Are we able to do this now? If not, any suggestions on how to accomplish this? 

![missingx](https://user-images.githubusercontent.com/20702895/41465806-9183c740-7097-11e8-8579-8cf044023596.png)

Maybe add an X to the top right corner. ( Suggestion )

**Comment by neptunian** [comment]
the images you see are the images in your state.  if you want to remove an image, remove it from "photos" prop of the gallery.  if you want to add an "x" to your UI use the custom ImageComponent prop.

**Comment by Olivr3** [comment]
@neptunian I am receiving the following error when I call `removeImage`.

![screenshot_48](https://user-images.githubusercontent.com/20702895/53300746-1c48ad00-3843-11e9-8b31-c22d946b0045.png)
![screenshot_49](https://user-images.githubusercontent.com/20702895/53300747-1c48ad00-3843-11e9-8ff2-8ae941981a69.png)


Is the prop not been passed down? 

How can we add events to the SelectedImage component? 

Once again, thanks! :smiley:
