### ISSUE TITLE
gallery layout isnt responsive on mobile

### ISSUE THREAD

**Issue by obiwankenoobi** [neptunian/react-photo-gallery#99]
I tried to layout a gallery on mobile size screen but it isn't changed anything. I still got the layout from the regular computer screen size with 3 tiny images in one line. I read in some issue here that its supposed to be responsive thats why Im asking (: 

![screen shot 2018-07-12 at 18 14 36](https://user-images.githubusercontent.com/24577941/42643037-dc488a08-8600-11e8-9d21-81703c4e30fb.png)

**Comment by obiwankenoobi** [comment]
ok I havn't seen [this](http://neptunian.github.io/react-photo-gallery/examples/dynamic-columns.html) I managed to fix it using your example thank you! perhaps there is a way to integrate this directly into the lib? Just a suggestion of course(: 

Thank you guys I love this lib!

**Comment by neptunian** [comment]
it used to be within the library but users want to be able to adjust the # of columns based on a breakpoint of their choosing.  its possible i'll have add some default responsive settings.
